default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    use_curiosity: false
    curiosity_strength: 0.01
    curiosity_enc_size: 128

BROThresholdBrain:
    batch_size: 2500
    beta: 3.5e-3
    buffer_size: 20000
    hidden_units: 30
    learning_rate: 4.0e-4
    max_steps: 5.0e5
    num_epoch: 10
    num_layers: 1
    time_horizon: 64
    summary_freq: 5000

BROBucketedBrain:
    batch_size: 96
    beta: 3.0e-3
    buffer_size: 10240
    hidden_units: 20
    learning_rate: 3.0e-4
    max_steps: 5.0e5
    num_epoch: 5
    num_layers: 1
    time_horizon: 64
    summary_freq: 5000

BROMovementBrain:
    batch_size: 2000
    beta: 3.0e-3
    buffer_size: 20000
    hidden_units: 20
    learning_rate: 3.75e-4
    max_steps: 1.0e6
    num_epoch: 5
    num_layers: 1
    time_horizon: 64
    summary_freq: 5000

BROClickBrain:
    batch_size: 64
    beta: 3.0e-3
    buffer_size: 8192
    hidden_units: 20
    learning_rate: 3.0e-4
    max_steps: 1.0e6
    num_epoch: 3
    num_layers: 1
    time_horizon: 64
    summary_freq: 5000
    
ShootingBirdsThresholdBrain:
    batch_size: 256
    beta: 5.0e-3
    buffer_size: 1024
    hidden_units: 256
    learning_rate: 3.0e-4
    max_steps: 3.0e5
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    summary_freq: 5000

ShootingBirdsBucketedBrain:
    batch_size: 96
    beta: 5.0e-3
    buffer_size: 10240
    hidden_units: 20
    learning_rate: 2.0e-4
    max_steps: 5.0e5
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    summary_freq: 5000
    
ShootingBirdsMovementBrain:
    batch_size: 128
    beta: 5.0e-3
    buffer_size: 1024
    hidden_units: 256
    learning_rate: 3.0e-4
    max_steps: 5.0e5
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    summary_freq: 5000

ShootingBirdsShootingBrain:
    batch_size: 48
    beta: 3.0e-3
    buffer_size: 512
    hidden_units: 20
    learning_rate: 2.0e-4
    max_steps: 5.0e5
    num_epoch: 3
    num_layers: 1
    time_horizon: 64
    summary_freq: 5000