default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 2.0e6
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 20000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals: 
        extrinsic:
            strength: 1.0
            gamma: 0.99

BROThresholdBrain:
    batch_size: 512
    beta: 3.5e-3
    buffer_size: 8192
    hidden_units: 120
    learning_rate: 3.0e-4
    num_epoch: 3
    num_layers: 2
    time_horizon: 64

BROMovementBrain:
    batch_size: 512
    beta: 3.5e-3
    buffer_size: 8192
    hidden_units: 120
    learning_rate: 3.00e-4
    num_epoch: 3
    num_layers: 2
    time_horizon: 64

BROBucketedBrain:
    batch_size: 256
    beta: 3.0e-3
    buffer_size: 8192
    hidden_units: 80
    learning_rate: 3.0e-4
    num_epoch: 4
    num_layers: 2
    time_horizon: 64

BROClickBrain:
    batch_size: 256
    beta: 3.0e-3
    buffer_size: 8192
    hidden_units: 80
    learning_rate: 3.0e-4
    num_epoch: 4
    num_layers: 2
    time_horizon: 64
    
SBThresholdBrain:
    batch_size: 512
    beta: 5.0e-2
    buffer_size: 8192
    hidden_units: 180
    learning_rate: 3.5e-4
    num_epoch: 3
    num_layers: 2
    time_horizon: 48
    
SBMovementBrain:
    batch_size: 512
    beta: 5.0e-2
    buffer_size: 8192
    hidden_units: 180
    learning_rate: 3.5e-4
    num_epoch: 3
    num_layers: 2
    time_horizon: 48

SBBucketedBrain:
    batch_size: 256
    beta: 5.0e-2
    buffer_size: 4096
    hidden_units: 100
    learning_rate: 3.25e-4
    num_epoch: 4
    num_layers: 2
    time_horizon: 48

SBClickingBrain:
    batch_size: 256
    beta: 5.0e-2
    buffer_size: 4096
    hidden_units: 100
    learning_rate: 3.25e-4
    num_epoch: 4
    num_layers: 2
    time_horizon: 48
