default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    use_curiosity: false
    curiosity_strength: 0.01
    curiosity_enc_size: 128

BROThresholdBrain:
    batch_size: 2500
    beta: 3.5e-3
    buffer_size: 20000
    hidden_units: 30
    learning_rate: 4.0e-4
    max_steps: 5.0e5
    num_epoch: 10
    num_layers: 1
    time_horizon: 64
    summary_freq: 5000

BROBucketedBrain:
    batch_size: 96
    beta: 3.0e-3
    buffer_size: 10240
    hidden_units: 20
    learning_rate: 3.0e-4
    max_steps: 5.0e5
    num_epoch: 5
    num_layers: 1
    time_horizon: 64
    summary_freq: 5000

BROMovementBrain:
    batch_size: 2000
    beta: 3.0e-3
    buffer_size: 20000
    hidden_units: 20
    learning_rate: 3.75e-4
    max_steps: 1.0e6
    num_epoch: 5
    num_layers: 1
    time_horizon: 64
    summary_freq: 5000

BROClickBrain:
    batch_size: 64
    beta: 3.0e-3
    buffer_size: 8192
    hidden_units: 20
    learning_rate: 3.0e-4
    max_steps: 1.0e6
    num_epoch: 3
    num_layers: 1
    time_horizon: 64
    summary_freq: 5000
    
SBThresholdBrain:
    batch_size: 512
    beta: 5.0e-2
    buffer_size: 8192
    hidden_units: 180
    learning_rate: 3.5e-4
    max_steps: 2.0e6
    num_epoch: 3
    num_layers: 2
    time_horizon: 48
    summary_freq: 5000

SBBucketedBrain:
    batch_size: 256
    beta: 5.0e-2
    buffer_size: 4096
    hidden_units: 100
    learning_rate: 3.25e-4
    max_steps: 2.0e6
    num_epoch: 4
    num_layers: 2
    time_horizon: 48
    summary_freq: 5000
    
SBMovementBrain:
    batch_size: 512
    beta: 5.0e-2
    buffer_size: 8192
    hidden_units: 180
    learning_rate: 3.5e-4
    max_steps: 2.0e6
    num_epoch: 3
    num_layers: 2
    time_horizon: 48
    summary_freq: 5000

SBClickingBrain:
    batch_size: 256
    beta: 5.0e-2
    buffer_size: 4096
    hidden_units: 100
    learning_rate: 3.25e-4
    max_steps: 2.0e6
    num_epoch: 4
    num_layers: 2
    time_horizon: 48
    summary_freq: 5000